/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

import java.awt.Color;
import java.awt.Component;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author Bishwajit
 */

class JLabelCellenderer extends JLabel implements TableCellRenderer {
 
    public JLabelCellenderer(String path) {
        setOpaque(true);
        setBackground(Color.WHITE);
         java.net.URL imgURL = getClass().getResource(path);
         this.setIcon(new ImageIcon(imgURL));
    }
 
    public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
      //  setText((String) value);
        if(isSelected){setBackground(new Color(184,207,229));}
        else{setBackground(Color.WHITE);}
        return this;
    }

    
}

public class PlayGround extends javax.swing.JFrame {

    /**
     * Creates new form PlayGround
     */
    HomePage.PlayerInfo myPlayerInfo;
    boolean moveFlag; // this is to determine whose turn
    int pile1, pile2;
    private DefaultTableModel myModel;
    BufferedImage img;
    int myMove;
    
    public PlayGround(HomePage.PlayerInfo playerInfo, int player_id, int p1, int p2, int move) {
        pile1 = p1;
        pile2 = p2;
        myPlayerInfo = playerInfo;
        moveFlag = player_id == 1;
        myMove = move;
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        init();
       
    }
    
    void init(){
        myModel = (DefaultTableModel) pile_1_table1.getModel();
        try {
            img = ImageIO.read(new File("./img/stone.png"));
        } catch (IOException ex) {
            System.out.println("stone image not retrieved!!!!!!!!");
        }
        if(myMove == 1)
            moveLabel.setText("    YOUR MOVE");
        else moveLabel.setText("OPPONENT'S MOVE");
        addStones();
        if(myMove == 0){
            removeButton.setEnabled(false);
        } else{
            ;
        }
    }
    
    void addStones(){
       
        ImageIcon icon = new ImageIcon("./img/stone.png");
        System.out.println("dikchik, model column class: " + myModel.getColumnClass(1).getClass());
        for(int i=0; i<pile1; i++){
            myModel.addRow(new Object[] { i+1 });
        }
        myModel  = (DefaultTableModel) pile_2_table.getModel();
        for(int i=0; i<pile2; i++){
            myModel.addRow(new Object[] { i+1 });
        }
        
        /*
        pile_1_table1.setRowHeight(img.getHeight());
        pile_2_table.setRowHeight(img.getHeight());
        System.out.println("pile: (" + pile1 + "," + pile2 + ")");
        for(int i=0; i<pile1; i++){
             myModel.addRow(new Object[]{img});
        }
        
        myModel = (DefaultTableModel) pile_2_table.getModel();
        for(int i=0; i<pile2; i++){
             myModel.addRow(new Object[]{img});
        }
        
        /*
        System.out.println("wowwww at addStones in playGround");
        pile_1_table1.setRowHeight(img.getHeight());
        pile_1_table1.getColumnModel().getColumn(1).setCellRenderer(new JLabelCellenderer("./img/stone.png"));
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playPanel = new javax.swing.JPanel();
        pileButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pile_2_table = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        pile_1_table1 = new javax.swing.JTable();
        removeButton = new javax.swing.JButton();
        informationPanel = new javax.swing.JPanel();
        moveLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        playPanel.setBackground(new java.awt.Color(255, 0, 0));

        pileButton2.setText("Remove Selected");
        pileButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pileButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText(" PLAYGRAOUND");

        pile_2_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "        PILE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(pile_2_table);

        pile_1_table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "        PILE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(pile_1_table1);

        removeButton.setText("Remove");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout playPanelLayout = new javax.swing.GroupLayout(playPanel);
        playPanel.setLayout(playPanelLayout);
        playPanelLayout.setHorizontalGroup(
            playPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playPanelLayout.createSequentialGroup()
                .addGroup(playPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(playPanelLayout.createSequentialGroup()
                        .addGroup(playPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(playPanelLayout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(playPanelLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(208, 208, 208)
                        .addComponent(pileButton2))
                    .addGroup(playPanelLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(removeButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        playPanelLayout.setVerticalGroup(
            playPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(playPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(playPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pileButton2)
                        .addGap(99, 99, 99))
                    .addGroup(playPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(playPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(removeButton)
                        .addContainerGap(22, Short.MAX_VALUE))))
        );

        informationPanel.setBackground(new java.awt.Color(255, 0, 0));

        moveLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        moveLabel.setText("    YOUR MOVE");

        javax.swing.GroupLayout informationPanelLayout = new javax.swing.GroupLayout(informationPanel);
        informationPanel.setLayout(informationPanelLayout);
        informationPanelLayout.setHorizontalGroup(
            informationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(moveLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addContainerGap())
        );
        informationPanelLayout.setVerticalGroup(
            informationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informationPanelLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(moveLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(playPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(informationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(playPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(informationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pileButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pileButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pileButton2ActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        // TODO add your handling code here:
        // here will lie my code.
    }//GEN-LAST:event_removeButtonActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel informationPanel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel moveLabel;
    private javax.swing.JButton pileButton2;
    private javax.swing.JTable pile_1_table1;
    private javax.swing.JTable pile_2_table;
    private javax.swing.JPanel playPanel;
    private javax.swing.JButton removeButton;
    // End of variables declaration//GEN-END:variables
}
